const express = require("express");
const swaggerUi = require("swagger-ui-express");
const swaggerJsdoc = require("swagger-jsdoc");
const swaggerAutogen = require('swagger-autogen')();
const swaggerDocument = require('./swagger-output.json');

// Swagger definition options
const swaggerOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Campaign API',
      version: '1.0.0',
      description: 'API documentation for Campaign Operations',
    },
    servers: [
      {
        url: 'http://localhost:9500',
        description: 'Local server',
      },
    ],
  },
  apis: ['./src/Controller/*.js'], // Points to your API route files
};

// Initialize swagger-jsdoc and generate Swagger docs dynamically
const swaggerSpec = swaggerJsdoc(swaggerOptions);

// Swagger server
const swaggerApp = express();

// Serve dynamically generated Swagger docs on 9501
swaggerApp.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));

// Serve static Swagger docs generated by swagger-autogen
swaggerApp.use('/api-docs1', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

swaggerApp.listen(9501, () => {
  console.log(`Swagger docs are running on http://localhost:9501/api-docs`);
});

// Swagger autogen setup to generate swagger-output.json
const doc = {
  info: {
    title: 'Campaign API',
    description: 'API documentation for Campaign Operations',
  },
  host: 'localhost:9500',  // Adjust this according to your host
  schemes: ['http'],  // Change to 'https' if necessary
};

const outputFile = './swagger-output.json';  // File where Swagger will be generated
const endpointsFiles = ['./index.js'];  // Path to your main server file where routes are defined

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  console.log('Swagger documentation generated');
});
